server:
  port: 8080
  address: 127.0.0.1

spring:
  datasource:
    url: jdbc:h2:mem:dev
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

